name: Deploy Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OpenSSH
        run: |
          sudo apt-get update
          sudo apt-get install openssh-client -y

      - name: Setup SSH
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "Host *" > ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config

      - name: Deploy
        env:
          USER: deploy
          HOST: ${{ secrets.DEPLOY_SERVER }}
        run: |
          ssh -i ~/.ssh/id_rsa $USER@$HOST << 'EOF'
            docker-compose down
            docker-compose pull
            docker-compose up -d
          EOF
        
